 const data = [
  {
    id:1,
    name: "Lorem ipsum Blender",
    price: 15.5,
    category:'Electronic',
    image : '/products/electronics-6.jpg',
  },
  {
    id:2,
    name: "Lorem ipsum Speaker",
    price: 9.5,
    category:'Electronic',
    image : '/products/electronics-1.jpg',
  },
  {
    id:3,
    name: "Lorem ipsum Camera",
    price: 10.1,
    category:'Electronic',
    image : '/products/electronics-2.jpg',
  },
  {
    id:4,
    name: "Lorem ipsum Fashion Coat",
    price: 35.5,
    category:'Fashion',
    image : '/products/cloth-1.jpg',
  },
  {
    id:5,
    name: "Lorem ipsum Fashion Jacket",
    price: 28.7,
    category:'Fashion',
    image : '/products/cloth-2.jpg',
  }, {
    id:6,
    name: "Lorem ipsum Fashion Dress",
    price: 33.4,
    category:'Fashion',
    image : '/products/women-4.jpg',
  },
  {
    id:7,
    name: "Lorem ipsum Jacket",
    price: 15.4,
    category:'Women',
    image : '/products/women-2.jpg',
  },
  {
    id:8,
    name: "Lorem ipsum Female Coat",
    price: 18.1,
    category:'Women',
    image : '/products/women-1.jpg',
  },
  {
    id:9,
    name: "Lorem ipsum Coat",
    price: 12.7,
    category:'Women',
    image : '/products/women-3.jpg',
  },
  {
    id:10,
    name: "Lorem ipsum Accessories",
    price: 15.9,
    category:'Accessories',
    image : '/products/accessories-1.jpg',
  },
  {
    id:11,
    name: "Lorem ipsum Accessories",
    price: 10.2,
    category:'Accessories',
    image : '/products/accessories-2.jpg',
  }, 
  {
    id:12,
    name: "Lorem ipsum Accessories",
    price: 20.1,
    category:'Accessories',
    image : '/products/accessories-4.jpg',
  },
  {
    id:13,
    name: "Lorem ipsum Furniture",
    price: 25.2,
    category:'Furniture',
    image : '/products/furniture-1.jpg',
  },
  {
    id:14,
    name: "Lorem ipsum Furniture",
    price: 18.4,
    category:'Furniture',
    image : '/products/furniture-2.jpg',
  },{
    id:15,
    name: "Lorem ipsum Furniture",
    price: 12.9,
    category:'Furniture',
    image : '/products/furniture-3.jpg',
  },
  {
    id:16,
    name: "Lorem ipsum Handmade",
    price: 10.4,
    category:'Handmade',
    image : '/products/handmade-1.jpg',
  },
  {
    id:17,
    name: "Lorem ipsum Handmade",
    price: 12.7,
    category:'Handmade',
    image : '/products/handmade-4.jpg',
  },{
    id:18,
    name: "Lorem ipsum Handmade",
    price: 20.1,
    category:'Handmade',
    image : '/products/handmade-3.jpg',
  },
  {
    id:19,
    name: "Lorem ipsum Book",
    price: 24.7,
    category:'Book',
    image : '/products/book-1.jpg',
  },
  {
    id:20,
    name: "Lorem ipsum Book",
    price: 14.4,
    category:'Book',
    image : '/products/book-2.jpg',
  },{
    id:21,
    name: "Lorem ipsum Book",
    price: 19.5,
    category:'Book',
    image : '/products/Book-3.jpg',
  },
  {
  id:22,
  name: "Lorem ipsum Kids",
  price: 29.5,
  category:'Kids',
  image : '/products/kid-3.jpg',
},
{
  id:23,
  name: "Lorem ipsum Food",
  price: 13.5,
  category:'Food',
  image : '/products/food-2.jpg',
},{
id:24,
name: "Lorem ipsum Flower",
price: 10.5,
category:'Flower',
image : '/products/flower-1.jpg',
},
{
  id:25,
  name: "Lorem ipsum Cakes",
  price: 20.3,
  category:'Cake',
  image : '/products/cake-4.jpg',
  },
  {
    id:26,
    name: "Lorem ipsum Flower",
    price: 24.3,
    category:'Flower',
    image : '/products/flower-2.jpg',
    },
      {
        id:27,
        name: "Lorem ipsum Cakes",
        price: 17.3,
        category:'Cake',
        image : '/products/cake-6.jpg',
        }
];
export default data;